name: Publish (m2 + draft)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Prepare release name
        run: |
          LEVIATHAN_VERSION=$(grep "leviathan =" gradle/leviathan.toml | cut -d '"' -f 2)
          RELEASE_TAG_NAME="release/v$LEVIATHAN_VERSION"
          
          echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME"
          echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME" >> $GITHUB_ENV
          
          echo "LEVIATHAN_VERSION=$LEVIATHAN_VERSION"
          echo "LEVIATHAN_VERSION=$LEVIATHAN_VERSION" >> $GITHUB_ENV

      - name: Execute Gradle build
        run: ./gradlew createLocalM2 -PPGP_KEY="${{secrets.PGP_KEY}}" -PPGP_PAS="${{secrets.PGP_PAS}}"

      - uses: actions/upload-artifact@v6
        with:
          name: m2
          path: build/m2
          if-no-files-found: error

      - name: Create zip file for release
        run: |
          cd build/m2
          zip -r m2.zip .

      - name: Create draft release
        run: |
          gh release create "${{ env.RELEASE_TAG_NAME }}" build/m2/m2.zip \
            --title "Leviathan ${{ env.LEVIATHAN_VERSION }}" \
            --generate-notes \
            --draft